### ISSUE TITLE
Missing module itsdangerous

### ISSUE THREAD

**Issue by cwmeijer** [mexca/mexca#30] opened 2022-09-26 09:47 UTC
I installed mexca using the version in the text sentiment analysis PR (https://github.com/mexca/mexca/pull/28/commits/4ad880f528454a746a92872ed930fd0d325fd1ee). When I ran pytest, I got the error below complaining about module ```itsdangerous```. Just installing it fixed it, so adding it to ```setup.cfg``` would solve my issue. Looking at the stack trace, this might not be a direct dependency from mexca but rather one from its dependencies, so I'm not sure if you would want to add it to your setup.cfg dependencies. 

PS C:\Users\ChristiaanMeijer\Documents\mexca\mexca> pytest
Traceback (most recent call last):
  File "C:\Users\ChristiaanMeijer\anaconda3\envs\mexca\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\ChristiaanMeijer\anaconda3\envs\mexca\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\ChristiaanMeijer\anaconda3\envs\mexca\Scripts\pytest.exe\__main__.py", line 7, in <module>
  File "C:\Users\ChristiaanMeijer\anaconda3\envs\mexca\lib\site-packages\_pytest\config\__init__.py", line 187, in console_main
    code = main()
  File "C:\Users\ChristiaanMeijer\anaconda3\envs\mexca\lib\site-packages\_pytest\config\__init__.py", line 145, in main
    config = _prepareconfig(args, plugins)
  File "C:\Users\ChristiaanMeijer\anaconda3\envs\mexca\lib\site-packages\_pytest\config\__init__.py", line 324, in _prepareconfig
    config = pluginmanager.hook.pytest_cmdline_parse(
  File "C:\Users\ChristiaanMeijer\anaconda3\envs\mexca\lib\site-packages\pluggy\_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
  File "C:\Users\ChristiaanMeijer\anaconda3\envs\mexca\lib\site-packages\pluggy\_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "C:\Users\ChristiaanMeijer\anaconda3\envs\mexca\lib\site-packages\pluggy\_callers.py", line 55, in _multicall
    gen.send(outcome)
  File "C:\Users\ChristiaanMeijer\anaconda3\envs\mexca\lib\site-packages\_pytest\helpconfig.py", line 102, in pytest_cmdline_parse
    config: Config = outcome.get_result()
  File "C:\Users\ChristiaanMeijer\anaconda3\envs\mexca\lib\site-packages\pluggy\_result.py", line 60, in get_result
    raise ex[1].with_traceback(ex[2])
  File "C:\Users\ChristiaanMeijer\anaconda3\envs\mexca\lib\site-packages\pluggy\_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
  File "C:\Users\ChristiaanMeijer\anaconda3\envs\mexca\lib\site-packages\_pytest\config\__init__.py", line 1017, in pytest_cmdline_parse
    self.parse(args)
  File "C:\Users\ChristiaanMeijer\anaconda3\envs\mexca\lib\site-packages\_pytest\config\__init__.py", line 1305, in parse
    self._preparse(args, addopts=addopts)
  File "C:\Users\ChristiaanMeijer\anaconda3\envs\mexca\lib\site-packages\_pytest\config\__init__.py", line 1188, in _preparse
    self.pluginmanager.load_setuptools_entrypoints("pytest11")
  File "C:\Users\ChristiaanMeijer\anaconda3\envs\mexca\lib\site-packages\pluggy\_manager.py", line 287, in load_setuptools_entrypoints
    plugin = ep.load()
  File "C:\Users\ChristiaanMeijer\anaconda3\envs\mexca\lib\importlib\metadata.py", line 86, in load
    module = import_module(match.group('module'))
  File "C:\Users\ChristiaanMeijer\anaconda3\envs\mexca\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "C:\Users\ChristiaanMeijer\anaconda3\envs\mexca\lib\site-packages\_pytest\assertion\rewrite.py", line 168, in exec_module
    exec(co, module.__dict__)
  File "C:\Users\ChristiaanMeijer\AppData\Roaming\Python\Python39\site-packages\dash\__init__.py", line 5, in <module>
    from .dependencies import (  # noqa: F401,E402
  File "C:\Users\ChristiaanMeijer\anaconda3\envs\mexca\lib\site-packages\_pytest\assertion\rewrite.py", line 168, in exec_module
    exec(co, module.__dict__)
  File "C:\Users\ChristiaanMeijer\AppData\Roaming\Python\Python39\site-packages\dash\dependencies.py", line 4, in <module>
    from ._validate import validate_callback
  File "C:\Users\ChristiaanMeijer\anaconda3\envs\mexca\lib\site-packages\_pytest\assertion\rewrite.py", line 168, in exec_module
    exec(co, module.__dict__)
  File "C:\Users\ChristiaanMeijer\AppData\Roaming\Python\Python39\site-packages\dash\_validate.py", line 5, in <module>
    import flask
  File "C:\Users\ChristiaanMeijer\AppData\Roaming\Python\Python39\site-packages\flask\__init__.py", line 7, in <module>
    from .app import Flask as Flask
  File "C:\Users\ChristiaanMeijer\AppData\Roaming\Python\Python39\site-packages\flask\app.py", line 52, in <module>
    from .sessions import SecureCookieSessionInterface
  File "C:\Users\ChristiaanMeijer\AppData\Roaming\Python\Python39\site-packages\flask\sessions.py", line 7, in <module>
    from itsdangerous import BadSignature
ModuleNotFoundError: No module named 'itsdangerous'

**Comment by maltelueken** [comment] 2022-09-26 14:49
For some reason I cannot reproduce this exact error, but when I tried to reproduce it, I got a similar error (there was a module missing). I added some version specifications for `transfomers` and `pyannote.audio`, which solved the issue on my machine. I hope this will fix this issue as well. Could you try installing it from the latest commit?

**Comment by maltelueken** [comment] 2023-08-31 08:56
This seems to be outdated, so I will close it for now.

**Closed by maltelueken** 2023-08-31 08:56 UTC
